name: django ERP
tagline: free your business
permalink: /blog/:year/:month/:day/:title
blog-url: /blog
project-url: https://github.com/djangoERPTeam/django-erp
project-download-url: https://github.com/djangoERPTeam/django-erp
wiki-url: https://github.com/djangoERPTeam/django-erp/wiki
markdown: redcarpet
pygments: true
